services:
  - type: web
    name: truthlens-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SIGHTENGINE_USER
        sync: false
      - key: SIGHTENGINE_SECRET
        sync: false
